### PR TITLE
Split Design of 3D Printed Parts

### PR DESCRIPTION
**Pull request by TekMason**
For those of you with 3D printers with smaller build plates.
Another side benefit is that more parts can be printed in a single run.

### CODE REVIEW

**Comment by TekMason** [comment]
Added Photo

**Review by MKme — APPROVED** [review]
Approved

**Comment by arcticcatmatt** [comment]
The L and the R are the identical file. I think you intended for the R to be a mirrored version of the L. I just printed them and couldn't get them together. Then I overlayed them in cad and verified that L and R are the identical part. I just made a mirrored arm and I am printing that now. 
This thing won't let me attach it.. sorry , my first post here, no idea how this works.

**Comment by TekMason** [comment]
My apologies.  Replaced the Right Frame STL file with the right one and
sent a Pull Request MKme

**Comment by arcticcatmatt** [comment]
I've taken the original file  from Erik Cederberg / 3DVerkstan / Faceshield.nu and made a click together version.  I'm printing them for a hospital here in NY. I can fit a bunch on my small print beds. 
clip2
clip




full bed

**Pull request merged**
